export const SPECIALITIES = [
    "CARDIOLOGIST",
    "PEDIATRICIAN",
    "NEUROLOGIST",
    "GASTROENTEROLOGIST",
    "PSYCHIATRIST",
    "DERMATOLOGIST",
    "UROLOGIST",
    "ONCOLOGIST",
    "ENDOCRINOLOGIST",
    "NEPHROLOGIST",
    "RHEUMATOLOGIST",
    "GYNECOLOGIST",
    "PULMONOLOGIST",
    "TRAUMATOLOGIST"
]